name: $(Build.SourceBranchName)_$(Build.Reason)_$(devops_buildNumber)

pr:
  branches:
    include:
    - testPublish

trigger:
  branches:
    include:
    - testPublish

pool:
  vmImage: 'vs2017-win2016'

variables:
  devops_buildNumber: $[counter(format(''), 1500)]
  APPVEYOR_REPO_BRANCH: $[coalesce(variables['System.PullRequest.TargetBranch'], variables['Build.SourceBranchName'])]
  APPVEYOR_REPO_COMMIT: $(Build.SourceVersion)

steps:
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true